export const Data = [
    {
      "ID":1,
      "Ticket_ID": 128652,
      "Employee_name": "Mr.Ethan Sullivan",
      "color":1,
      "Area_of_problem":"Blood Pressure",
      "Request_type":"Open Request",
      "Request_Type_no": 1,
      "Priority":"High",
      "key":3,
      "Raised_Date":"16.Jan.2023",
    },
    {
      "ID":2,
      "Ticket_ID": 523497,
      "Employee_name": "Mr.Benjamin Lee",
      "color":1,
      "Area_of_problem":"Blood Pressure",
      "Request_type":"Modify Request",
      "Request_Type_no": 2,
      "Priority":"High",
      "key":3,
      "Raised_Date":"16.Jan.2023"
    },
  {
    "ID":3,
      "Ticket_ID": 871236,
      "Employee_name": "Mr.Alexander Collins",
      "color":1,
      "Area_of_problem":"Back Pain",
      "Request_type":"Escalation",
      "Request_Type_no": 3,
      "Priority":"High",
      "key":3,
      "Raised_Date":"16.Jan.2023"
    },
    {
      "ID":4,
      "Ticket_ID": 649815,
      "Employee_name": "Mr.Lucas Martinez",
      "color":2,
      "Area_of_problem":"Blood Pressure",
      "Request_type":"Open Request",
      "Request_Type_no": 1,
      "Priority":"Low",
      "key":1,
      "Raised_Date":"16.Jan.2023"
    },
    {
      "ID":5,
      "Ticket_ID": 925364,
      "Employee_name": "Mr.Sophia Anderson",
      "color":1,
      "Area_of_problem":"Back Pain",
      "Request_type":"Open Request",
      "Request_Type_no": 1,
      "Priority":"High",
      "key":3,
      "Raised_Date":"16.Jan.2023"
    },
    {
      "ID":6,
      "Ticket_ID": 347582,
      "Employee_name": "Mr.Benjamin Scott",
      "color":3,
      "Area_of_problem":"Diabetes",
      "Request_type":"Open Request",
      "Request_Type_no": 1,
      "Priority":"Mid",
      "key":2,
      "Raised_Date":"16.Jan.2023"
    },
    {
      "ID":7,
      "Ticket_ID": 712549,
      "Employee_name": "Mr.Ava Rodriguez",
      "color":1,
      "Area_of_problem":"Kindey Stone",
      "Request_type":"Open Request",
      "Request_Type_no": 1,
      "Priority":"High",
      "key":3,
      "Raised_Date":"16.Jan.2023"
    },
    {
      "ID":8,
      "Ticket_ID": 486193,
      "Employee_name": "Mr.Alexander Collins",
      "color":3,
      "Area_of_problem":"Hypertension",
      "Request_type":"Escalation",
      "Request_Type_no": 3,
      "Priority":"Mid",
      "key":2,
      "Raised_Date":"16.Jan.2023"
    },
    {
      "ID":9,
      "Ticket_ID": 635971,
      "Employee_name": "Mr.Ethan Sullivan",
      "Area_of_problem":"Insomnia",
      "color":2,
      "Request_type":"Modify Request",
      "Request_Type_no": 2,
      "Priority":"Low",
      "key":1,
      "Raised_Date":"16.Jan.2023"
    }
  ]